services:
  repocket:
    # Official Repocket image
    image: repocket/repocket:latest

    container_name: repocket-container

    # Environment variables for Repocket credentials
    environment:
      - RP_EMAIL=${RP_EMAIL}
      - RP_API_KEY=${RP_API_KEY}

    restart: always
