services:
  presearch-node:
    # Official Presearch node image
    image: ${DOCKER_IMAGE:-presearch/node:latest}
    container_name: presearch-node
    # Environment variables for registration
    environment:
      - REGISTRATION_CODE=${PRESEARCH_REGISTRATION_CODE}
    # Volume for data persistence
    volumes:
      - ${PRESEARCH_VOLUME_PATH:-presearch-node-storage}:/app/node
    restart: unless-stopped

volumes:
  presearch-node-storage:
